=begin
#Static OpenAPI document of Push API resource

#Push API resources Open API documentation

The version of the OpenAPI document: 0.4.0

Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Databox::PushDataAttribute
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Databox::PushDataAttribute do
  let(:instance) { Databox::PushDataAttribute.new }

  describe 'test an instance of PushDataAttribute' do
    it 'should create an instance of PushDataAttribute' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Databox::PushDataAttribute)
    end
  end

  describe 'test attribute "key"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "value"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
