=begin
#Static OpenAPI document of Push API resource

#Push API resources Open API documentation

The version of the OpenAPI document: 0.4.2

Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Databox::State
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Databox::State do
  let(:instance) { Databox::State.new }

  describe 'test an instance of State' do
    it 'should create an instance of State' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Databox::State)
    end
  end

end
