=begin
#Static OpenAPI document of Push API resource

#Push API resources Open API documentation

The version of the OpenAPI document: 0.4.2

Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'date'
require 'time'

module Databox
  class State
    DOWN = "DOWN".freeze
    UP = "UP".freeze

    def self.all_vars
      @all_vars ||= [DOWN, UP].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if State.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #State"
    end
  end
end
