=begin
#Static OpenAPI document of Push API resource

#Push API resources Open API documentation

The version of the OpenAPI document: 0.4.1

Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

module Databox
  VERSION = '2.0.2'
end
