# -*- encoding: utf-8 -*-

=begin
#Static OpenAPI document of Push API resource

#Push API resources Open API documentation

The version of the OpenAPI document: 0.4.1

Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "databox/version"

Gem::Specification.new do |s|
  s.name        = "databox"
  s.version     = Databox::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Databox"]
  s.email       = [""]
  s.homepage    = "https://databox.com/"
  s.summary     = "Static OpenAPI document of Push API resource Ruby Gem"
  s.description = "SDK Client for using Databox Push API feature"
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = {}

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
